FROM node:20-alpine AS dev

# Prepare app directory
WORKDIR /app
COPY package*.json .

# Install all dependencies frozen lock
RUN npm install --frozen-lockfile

# Run angular in dev mode
CMD ["npx", "ng", "serve", "--host=0.0.0.0", "--proxy-config=/config/docker.proxy.config.json"]