name: scicat_dev

services:
    mongodb:
        container_name: scicat_mongodb
        image: mongo:4.2
        volumes:
            - ./local/mongodb:/data/db
    backend:
        container_name: scicat_backend
        build:
            context: ./SciCat/backend
            dockerfile: ../../patch/Dockerfile.backend
            target: dev
        depends_on:
            - mongodb
        volumes:
            - ./SciCat/backend:/app
            # Config is loaded via backend.config.json
            - ./config/backend/frontend.config.json:/app/src/config/frontend.config.json
        environment:
            # Link to the mongo container (see above)
            MONGODB_URI: mongodb://mongodb:27017/
            EXPRESS_SESSION_SECRET: a_scicat_secret
            JWT_SECRET: a_scicat_secret
            PORT: 3000
        ports:
            - 4201:3000
    frontend:
        container_name: scicat_frontend
        build:
            context: ./SciCat/frontend
            dockerfile: ../../patch/Dockerfile.frontend
            target: dev
        ports:
            - 4200:4200
        volumes:
            - ./SciCat/frontend:/app
            - ./config/frontend:/config
